### ISSUE TITLE
Fix `zinit` issue

### ISSUE THREAD

**Issue by nathanshelly** [nathanshelly/.files#67]
This line:

https://github.com/nathanshelly/.files/blob/2978a9c128fdbf5fafc34eb115013c8fc8ae9067/zsh/plugins.zsh#L50

causes the following output on every new shell creation:

```
(eval):1: ZPLGM: assignment to invalid subscript range
```

**Comment by Lugoues** [comment]
Since you are one of the few google results when looking for this error. The fix is to use `ZINIT` instead of `ZPLGM`. :)
https://github.com/zdharma/zinit/blob/master/CHANGELOG.md#L15

**Comment by nathanshelly** [comment]
thanks @Lugoues!
